### ISSUE TITLE
Plant drop issues

### ISSUE THREAD

**Issue by blipadouzi** [TeamMetallurgy/Agriculture#12]
My understanding was plants were supposed to work much like carrots and potatoes, dropping their items when broken, and dropping even more items when fully grown.

As it is, a fully grown cinnamon or vanilla plant can simply be clicked once, and the "fruit" will drop leaving the plant intact.  Continuing to break the plant will drop the plant itself.

**Comment by Shadowclaimer** [comment]
Intentional.

Spices drop one piece each time they're hit and they lose a stage, at bottom stage they drop their own plant. Spices are not meant to be plantable en masse.

**Comment by odininon** [comment]
But apparently Keith left in some debug code where you could crops by clicking on them... At least that is what lclc98 told me yesterday.

**Comment by Shadowclaimer** [comment]
Ah what else is new =P
